"""add_sage_account_reference_to_orders

Revision ID: 219d7b8375b4
Revises: ed904b2d3d1f
Create Date: 2026-07-06 19:06:18.106055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '219d7b8375b4'
down_revision: Union[str, Sequence[str], None] = 'ed904b2d3d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sage_account_reference', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sage_account_reference')
    # ### end Alembic commands ###
