"""add_description_to_products

Revision ID: 2b8a597a27fa
Revises: 3772dae57fbd
Create Date: 2026-07-22 01:07:36.148314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b8a597a27fa'
down_revision: Union[str, Sequence[str], None] = '3772dae57fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
