"""add_must_change_password_to_user

Revision ID: 81bfc2baaed6
Revises: 329ae28d4988
Create Date: 2026-07-09 16:21:36.589190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '81bfc2baaed6'
down_revision: Union[str, Sequence[str], None] = '329ae28d4988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
