"""add_is_approved_to_shop

Revision ID: a6a75bf89fc3
Revises: 81bfc2baaed6
Create Date: 2026-07-13 21:29:14.387756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6a75bf89fc3'
down_revision: Union[str, Sequence[str], None] = '81bfc2baaed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'is_approved')
    # ### end Alembic commands ###
