"""Add sage sync columns

Revision ID: b5171db73944
Revises: 20260612_0007
Create Date: 2026-07-02 15:47:16.340304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5171db73944'
down_revision: Union[str, Sequence[str], None] = '20260612_0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sage_order_number', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('sync_notes', sa.String(length=1000), nullable=True))
    op.add_column('shops', sa.Column('sage_account_reference', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'sage_account_reference')
    op.drop_column('orders', 'sync_notes')
    op.drop_column('orders', 'sage_order_number')
    # ### end Alembic commands ###
