"""Add profile and sync fields to shops

Revision ID: b9e4ed14262d
Revises: a6a75bf89fc3
Create Date: 2026-07-17 16:49:05.443155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9e4ed14262d'
down_revision: Union[str, Sequence[str], None] = 'a6a75bf89fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('shops', sa.Column('telephone_2', sa.String(length=50), nullable=True))
    op.add_column('shops', sa.Column('telephone_3', sa.String(length=50), nullable=True))
    op.add_column('shops', sa.Column('needs_sage_sync', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'needs_sage_sync')
    op.drop_column('shops', 'telephone_3')
    op.drop_column('shops', 'telephone_2')
    op.drop_column('shops', 'contact_name')
    # ### end Alembic commands ###
