"""add_slug_and_category_ids

Revision ID: ed904b2d3d1f
Revises: f0357afb6496
Create Date: 2026-07-02 19:35:55.778270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed904b2d3d1f'
down_revision: Union[str, Sequence[str], None] = 'f0357afb6496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.add_column('subcategories', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subcategories_slug'), 'subcategories', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategories_slug'), table_name='subcategories')
    op.drop_column('subcategories', 'slug')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.alter_column('products', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
