"""Update shop schema, add VAT and salesperson to orders

Revision ID: f0357afb6496
Revises: b5171db73944
Create Date: 2026-07-02 17:19:10.318773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0357afb6496'
down_revision: Union[str, Sequence[str], None] = 'b5171db73944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('vat_rate', sa.Float(), server_default='20.0', nullable=False))
    op.add_column('order_items', sa.Column('vat_amount', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('orders', sa.Column('salesperson_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('total_vat', sa.Float(), server_default='0.0', nullable=False))
    op.create_index(op.f('ix_orders_salesperson_id'), 'orders', ['salesperson_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['salesperson_id'], ['id'])
    
    # Rename columns to preserve data
    op.alter_column('shops', 'shop_name', new_column_name='name')
    op.alter_column('shops', 'phone', new_column_name='phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename columns back
    op.alter_column('shops', 'name', new_column_name='shop_name')
    op.alter_column('shops', 'phone_number', new_column_name='phone')
    
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_salesperson_id'), table_name='orders')
    op.drop_column('orders', 'total_vat')
    op.drop_column('orders', 'salesperson_id')
    op.drop_column('order_items', 'vat_amount')
    op.drop_column('order_items', 'vat_rate')
    # ### end Alembic commands ###
